-- Create splitwise_connections table to store OAuth tokens per user
-- removed strict REFERENCES auth.users(id) because the frontend is currently local-storage based
-- and might not have a real supabase logged-in user yet.
CREATE TABLE IF NOT EXISTS splitwise_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL, 
  splitwise_user_id TEXT,
  access_token TEXT NOT NULL,
  access_token_secret TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_user_splitwise UNIQUE (user_id)
);

-- Plantão de Fluxo de Caixa: Link properties to Splitwise groups
CREATE TABLE IF NOT EXISTS property_splitwise_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  property_name TEXT NOT NULL,
  splitwise_group_id TEXT NOT NULL,
  matched_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_property_link UNIQUE (user_id, property_name)
);

-- RLS Policies (Optional but recommended if exposing directly, simplified for now)
ALTER TABLE splitwise_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_splitwise_links ENABLE ROW LEVEL SECURITY;

-- Allow public access for this demo/MVP if no auth is present, 
-- or stick to policies that assume auth.uid() matches user_id (which works if we simulate auth later)
-- For now, we will leave RLS enabled but since we are using SERVICE_ROLE key in backend, 
-- backend bypasses RLS. Frontend doesn't access these tables directly.
